weights: .\yolov5\runs\train\yolov5m-freeze10-100epoch2\weights\last.pt
cfg: ''
data: ./yolov5/data/custom_dataset.yaml
hyp: yolov5\data\hyps\hyp.scratch.yaml
epochs: 100
batch_size: 64
imgsz: 640
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: yolov5\runs\train
name: yolov5m-freeze10-100epoch
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 24
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: yolov5\runs\train\yolov5m-freeze10-100epoch2
