weights: ./yolov5/runs/train/yolov5m-freeze10-100epoch2/weights/last.pt
cfg: C:\Users\bradyy\Desktop\CV\yolov5\models\yolov5m.yaml
data: ./yolov5/data/custom_dataset.yaml
hyp: C:\Users\bradyy\Desktop\CV\yolov5\data\hyps\hyp.finetune.yaml
epochs: 100
batch_size: 24
imgsz: 512
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: disk
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: yolov5\runs\train
name: 5m-unfreeze-24-100ep
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: yolov5\runs\train\5m-unfreeze-24-100ep
